version: "3"

services:
  xiaozhi-mcp-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    image: "angelinmylife/xiaozhi-mcp-bridge:latest"
    container_name: "xiaozhi-mcp-bridge"
    user: "root"
    privileged: true
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config.json:/app/config.json:ro"
    environment:
      CONFIG_PATH: "config.json"
      MCP_ENDPOINT: "wss://api.xiaozhi.me/mcp/?token=eyJhbGcx..."

    restart: always

